# Uses https://github.com/marketplace/actions/build-and-push-docker-images
name: Deliver to DockerHub
# TODO only on published releases
#on:
#  release:
#    types: [published]
on: [push, pull_request]
jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          echo "POPULARE_DB_BUILD_VERSION=$(PYTHONPATH=. python -c 'from populare_db_proxy import __version__; print(__version__)')" >> $GITHUB_ENV
      - name: Check version
        run: |
          echo $POPULARE_DB_BUILD_VERSION
          echo ${{ env.POPULARE_DB_BUILD_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kostaleonard/populare_db_proxy:latest,kostaleonard/populare_db_proxy:$POPULARE_DB_BUILD_VERSION